# Test your FastAPI endpoints

GET http://localhost:5080/1/1
Accept: application/json

###

GET http://localhost:5080/docs
Accept: application/json

###

GET http://localhost/pixel/docs
Accept: application/json

###


GET http://localhost/pixel/1/1
Accept: application/json

###
