# Staging environment - as production except for domain
services:
  frontend:
    image: ghcr.io/nismod/jsrat-frontend:0.4.17
    platform: linux/amd64
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    image: ghcr.io/nismod/jsrat-backend:0.2
    platform: linux/amd64
    build: ./backend
    ports:
      - "3001:80"
    env_file:
      - ./envs/.backend.env

  vector-tileserver:
    image: ghcr.io/nismod/jsrat-vector-tileserver:0.1
    platform: linux/amd64
    build:
      context: ./tileserver/vector
    command:
      [
        "tileserver-gl-light",
        "-c",
        "config.json",
        "-p",
        "8080",
        "--verbose",
        "-u",
        "https://jamaica.infrastructureresilience.org/vector",
      ]
    ports:
      - "3002:8080"
    volumes:
      - ./tileserver/vector/data:/data
      - ./tileserver/vector/config.json:/config.json

  raster-tileserver:
    image: ghcr.io/nismod/jsrat-raster-tileserver:0.1
    platform: linux/amd64
    build: ./tileserver/raster
    ports:
      - "3003:5000"
    volumes:
      - ./tileserver/raster/data:/data
      - ./tileserver/raster/config.toml:/config.toml
    environment:
      - TC_DRIVER_PATH=/data/terracotta.sqlite
      - TC_RESAMPLING_METHOD=nearest
      - TC_REPROJECTION_METHOD=nearest
      - TC_PNG_COMPRESS_LEVEL=1
