// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AttributesReadAttributesData, AttributesReadAttributesErrors, AttributesReadAttributesResponses, FeaturesReadFeatureData, FeaturesReadFeatureErrors, FeaturesReadFeatureResponses, FeaturesReadProtectedFeaturesData, FeaturesReadProtectedFeaturesErrors, FeaturesReadProtectedFeaturesResponses, FeaturesReadSortedFeaturesData, FeaturesReadSortedFeaturesErrors, FeaturesReadSortedFeaturesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Feature
 */
export const featuresReadFeature = <ThrowOnError extends boolean = false>(options: Options<FeaturesReadFeatureData, ThrowOnError>) => (options.client ?? client).get<FeaturesReadFeatureResponses, FeaturesReadFeatureErrors, ThrowOnError>({ url: '/features/{feature_id}', ...options });

/**
 * Read Sorted Features
 */
export const featuresReadSortedFeatures = <ThrowOnError extends boolean = false>(options: Options<FeaturesReadSortedFeaturesData, ThrowOnError>) => (options.client ?? client).get<FeaturesReadSortedFeaturesResponses, FeaturesReadSortedFeaturesErrors, ThrowOnError>({ url: '/features/sorted-by/{field_group}', ...options });

/**
 * Read Protected Features
 *
 * Get all adaptation options, by feature ID and layer, for features
 * protected by a given protector feature.
 */
export const featuresReadProtectedFeatures = <ThrowOnError extends boolean = false>(options: Options<FeaturesReadProtectedFeaturesData, ThrowOnError>) => (options.client ?? client).get<FeaturesReadProtectedFeaturesResponses, FeaturesReadProtectedFeaturesErrors, ThrowOnError>({ url: '/features/{protector_id}/protected-by', ...options });

/**
 * Read Attributes
 */
export const attributesReadAttributes = <ThrowOnError extends boolean = false>(options: Options<AttributesReadAttributesData, ThrowOnError>) => (options.client ?? client).post<AttributesReadAttributesResponses, AttributesReadAttributesErrors, ThrowOnError>({
    url: '/attributes/{field_group}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
