// This file is auto-generated by @hey-api/openapi-ts

export type Adaptation = {
    adaptation_cost: number;
    avoided_ead_amin: number;
    avoided_ead_mean: number;
    avoided_ead_amax: number;
    avoided_eael_amin: number;
    avoided_eael_mean: number;
    avoided_eael_amax: number;
    hazard: string;
    rcp: string;
    adaptation_name: string;
    adaptation_protection_level: number;
};

export type ExpectedDamage = {
    ead_amin: number;
    ead_mean: number;
    ead_amax: number;
    eael_amin: number;
    eael_mean: number;
    eael_amax: number;
    hazard: string;
    rcp: string;
    epoch: (string | number);
    protection_standard: number;
};

export type FeatureListItemOut_float_ = {
    id: number;
    string_id: string;
    layer: string;
    bbox_wkt: string;
    value: number;
};

export type FeatureOut = {
    id: number;
    string_id: string;
    layer: string;
    sublayer?: (string | null);
    properties: {
        [key: string]: unknown;
    };
    damages_expected?: Array<ExpectedDamage>;
    damages_return_period?: Array<ReturnPeriodDamage>;
    damages_npv?: Array<NPVDamage>;
    adaptation?: Array<Adaptation>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type NPVDamage = {
    ead_amin: number;
    ead_mean: number;
    ead_amax: number;
    eael_amin: number;
    eael_mean: number;
    eael_amax: number;
    hazard: string;
    rcp: string;
};

export type Page_FeatureListItemOut_float__ = {
    items: Array<FeatureListItemOut_float_>;
    total: (number | null);
    page: (number | null);
    size: (number | null);
    pages?: (number | null);
};

export type ProtectedFeatureListItem = {
    id: number;
    string_id: string;
    layer: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    adaptation_cost: number;
    avoided_ead_mean: number;
    avoided_eael_mean: number;
    hazard: string;
    rcp: number;
};

export type ReturnPeriodDamage = {
    exposure: number;
    damage_amin: number;
    damage_mean: number;
    damage_amax: number;
    loss_amin: number;
    loss_mean: number;
    loss_amax: number;
    hazard: string;
    rcp: string;
    epoch: (string | number);
    rp: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AttributesReadAttributesData = {
    dimensions: string;
    field: string;
    fieldGroup: string;
    layer: string;
    parameters: string;
    requestBody: Array<(number)>;
};

export type AttributesReadAttributesResponse = ({
    [key: string]: (unknown | null);
});

export type FeaturesReadFeatureData = {
    featureId: number;
};

export type FeaturesReadFeatureResponse = (FeatureOut);

export type FeaturesReadSortedFeaturesData = {
    assetType?: (string | null);
    dimensions: string;
    field: string;
    fieldGroup: string;
    layer?: (string | null);
    page?: number;
    parameters: string;
    sector?: (string | null);
    size?: number;
    subsector?: (string | null);
};

export type FeaturesReadSortedFeaturesResponse = (Page_FeatureListItemOut_float__);

export type FeaturesReadProtectedFeaturesData = {
    protectionLevel: number;
    protectorId: number;
    rcp: string;
};

export type FeaturesReadProtectedFeaturesResponse = (Array<ProtectedFeatureListItem>);