# union of jamaica-infrastructure and irv-jamaica backend and ETL requirements as of 2025-08-15
# to install this environment:
# micromamba create -f environment.yml -y
name: irv-jamaica-etl
channels:
  - conda-forge  # majority of dependencies
  - nodefaults  # avoid anaconda license issues
dependencies:
  - python~=3.12
  - pip:
    - -e ../backend
    - nismod-snail==0.5.3
    - snkit~=1.9.0
    - terracotta==0.9.1  # required for ETL
  - bioconda::snakemake~=8.30.0
  - black
  - fiona~=1.10.0
  - geopandas~=1.0.1
  - python-igraph~=0.11.6
  - matplotlib~=3.9.2
  - networkx~=3.3
  - numpy~=2.1.1
  - openpyxl~=3.1.5
  - pandas~=2.2.2
  - pathos~=0.3.2
  - pyarrow~=21.0.0
  - rasterio~=1.3.11
  - rioxarray~=0.17.0
  - SALib~=1.5.1
  - scipy~=1.14.1
  - shapely~=2.0.6
  - tippecanoe~=2.78.0
  - tqdm
  - ujson~=5.10.0
  - xarray~=2024.9.0
  # irv-jamaica/backend
  - fastapi-pagination~=0.13
  - fastapi~=0.116
  - geoalchemy2~=0.18  # also used in ETL
  - psycopg2-binary==2.9.10
  - pydantic~=2.11
  - uvicorn~=0.33
