name: Clean up untagged GHCR images

on:
  push:
    branches:
      - cleanup-ghcr
  workflow_dispatch:

jobs:
  ghcr-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean up untagged images
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: org # or user
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-owner: ${{ github.repository_owner }}
          package-name: jsrat-frontend
          delete-untagged: true
