# .github/workflows/storybook-tests.yml

name: "Storybook Tests"
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.54.2-noble
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.nvmrc
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test-storybook
